export const EN_US_COPY = {
  settings: 'Settings',
  closeSettings: 'Close settings',
  agentContextRestored: 'Agent context restored',
  agentContextRestoreSkipped: 'Agent context restore skipped',
  connectDeviceTask: 'Connect device',
  captureScreenTask: 'Capture screen',
  deviceConnected: 'Device connected',
  deviceDisconnected: 'Device disconnected',
  disconnectDeviceTask: 'Disconnect device',
  executeActionTask: 'Execute action',
  executedAction: (preview: string) => `Executed ${preview}`,
  failedAction: (preview: string) => `Failed ${preview}`,
  failedToDownloadAdbKeyboard: (status: number) =>
    `Failed to download ADB Keyboard APK: HTTP ${status}.`,
  language: 'Language',
  languageSystem: 'System default',
  languageChinese: '中文',
  languageEnglish: 'English',
  appDescription:
    'Browser-based Android automation console for WebADB and OpenAI-compatible vision models.',
  githubRepository: 'GitHub repository',
  repositoryStats: 'Repository stats',
  stars: 'Stars',
  forks: 'Forks',
  openIssues: 'Open issues',
  githubStatsError: 'Could not load GitHub stats right now.',
  theme: 'Theme',
  themeSystem: 'System',
  themeLight: 'Light',
  themeDark: 'Dark',
  configurationPanel: 'Configuration',
  collapseConfigurationPanel: 'Collapse configuration panel',
  expandConfigurationPanel: 'Expand configuration panel',
  openConfigurationSection: (section: string) => `Open ${section}`,
  webUsbReady: 'ready',
  webUsbMissing: 'missing',
  model: 'Model',
  noModel: 'No model',
  modelSettings: 'Model settings',
  baseUrl: 'Base URL',
  apiKey: 'API Key',
  streamModelResponses: 'Stream model responses',
  device: 'Device',
  noDevice: 'No device',
  deviceDetails: 'Device details',
  serial: 'Serial',
  currentApp: 'Current app',
  package: 'Package',
  activity: 'Activity',
  keyboard: 'Keyboard',
  usbDebuggingRequired: 'USB debugging required',
  connect: 'Connect',
  adbConnectionHelpLabel: 'ADB connection help',
  adbConnectionHelpText:
    'If the connection fails, run adb kill-server in your terminal, then reconnect the device.',
  disconnect: 'Disconnect',
  capture: 'Capture',
  configureTextInput: 'Configure text input',
  adbKeyboardConfigured: 'Text input configured',
  runDoctor: 'Run Doctor',
  doctorChecks: 'Doctor checks',
  doctorSummary: 'Doctor summary',
  installedApps: 'Installed apps',
  appSearch: 'App search',
  launchApp: 'Launch',
  launchInstalledApp: (name: string) => `Launch ${name}`,
  noInstalledApps: 'No installed apps found',
  deviceOptions: 'Device options',
  directCommands: 'Direct commands',
  directCommand: 'Direct command',
  tapX: 'Tap X',
  tapY: 'Tap Y',
  runTap: 'Run Tap',
  swipeFromX: 'From X',
  swipeFromY: 'From Y',
  swipeToX: 'To X',
  swipeToY: 'To Y',
  runSwipe: 'Run Swipe',
  directText: 'Text',
  runType: 'Run Type',
  runBack: 'Back',
  runHome: 'Home',
  runEnter: 'Enter',
  useAdbKeyboard: 'Use ADB Keyboard for text',
  confirmSensitiveActions: 'Confirm sensitive actions',
  sensitiveActionTitle: 'Sensitive action requested',
  sensitiveActionPrompt: 'Execute it?',
  actionSettle: 'Action settle (ms)',
  doubleTapInterval: 'Double tap interval (ms)',
  keyboardStep: 'Keyboard step (ms)',
  supportedActions: 'Supported actions',
  capabilities: [
    'Launch',
    'Tap',
    'Type',
    'Swipe',
    'Back',
    'Home',
    'Long press',
    'Double tap',
    'Wait',
    'Take over',
  ],
  androidScreenshot: 'Android screenshot',
  expandedAndroidScreenshot: 'Expanded screenshot for Android screenshot',
  screenshotInteractionLayer: 'Screenshot interaction layer',
  runGeneratedAction: 'Run generated action',
  clearGeneratedAction: 'Clear generated action',
  openScreenshotFor: (title: string) => `Open screenshot for ${title}`,
  screenshotDialogFor: (title: string) => `Screenshot for ${title}`,
  closeScreenshotPreview: 'Close screenshot preview',
  screenshotZoomControls: 'Screenshot zoom controls',
  zoomInScreenshot: 'Zoom in screenshot',
  zoomOutScreenshot: 'Zoom out screenshot',
  resetScreenshotZoom: 'Reset screenshot zoom',
  showPhoneFullscreen: 'Show phone fullscreen',
  exitPhoneFullscreen: 'Exit phone fullscreen',
  fullscreenPhonePreview: 'Fullscreen phone preview',
  noScreenshot: 'No screenshot',
  chat: 'Chat',
  history: 'History',
  openHistorySidebar: 'Open history sidebar',
  closeHistorySidebar: 'Close history sidebar',
  recentChats: 'Recent chats',
  historyEmpty: 'No chat history yet.',
  historyNoMatches: 'No matching chats.',
  historySearchAria: 'Search chat history',
  historySearchPlaceholder: 'Search history...',
  historySearchClear: 'Clear history search',
  openHistoryThread: (title: string) => `Open chat ${title}`,
  deleteHistoryThread: (title: string) => `Delete chat ${title}`,
  conversation: 'Conversation',
  noMessages: 'No messages yet',
  chatMessage: 'Chat message',
  chatPlaceholder: 'Send a follow-up instruction...',
  loopGuardStopped: 'Loop guard stopped the run',
  manualTakeoverRequested: 'Manual takeover requested',
  maxStepsReached: 'Max steps reached',
  send: 'Send',
  stopRun: 'Stop run',
  newChat: 'New chat',
  newChatStarted: 'New chat started',
  noAdbKeyboardDownloadSupport: 'This browser cannot download the ADB Keyboard APK.',
  typeMessageFirst: 'Type a message first.',
  runAgentTask: 'Run agent',
  runStopped: 'Run stopped',
  waitForCurrentRun: 'Wait for the current run to finish.',
  maxSteps: 'Max steps',
  pendingAction: 'Pending action',
  screenCaptured: 'Screen captured',
  step: 'Step',
  stepPreview: (index: number, preview: string) => `Step ${index}: ${preview}`,
  stepAction: 'Action',
  stepResult: 'Result',
  stepDetails: 'Details',
  stepModelOutput: 'Model output',
  stepTiming: (totalMs: number) => `Total ${totalMs} ms`,
  stepNoResult: 'Waiting for result',
  stepStatusPlanned: 'Planned',
  stepStatusRunning: 'Running',
  stepStatusExecuted: 'Executed',
  stepStatusFailed: 'Failed',
  stepStatusDone: 'Done',
  stepStatusAwaitingReview: 'Needs review',
  stepStatusTakeover: 'Takeover',
  none: 'None',
  acknowledge: 'Acknowledge',
  finish: 'Finish',
  execute: 'Execute',
  user: 'User',
  assistant: 'Assistant',
  observation: 'Observation',
  taskComplete: 'Task complete',
  runLog: 'Run Log',
  clear: 'Clear',
  noEvents: 'No events yet',
  userMessage: 'User message',
  userMessageQueued: 'User message queued',
} as const
